//Faça um algoritmo para calcular a tabuada do 4 e 8.


























algoritmo "Tabuada 4 e 8"

var
   contador:inteiro
inicio

   escreval("Mostrando a tabuada do 4")
   para contador <- 0 ate 10 faca
      escreval("4 X ", contador, " = ", 4*contador)
   fimpara
   
   escreval("Mostrando a tabuada do 8")
   para contador <- 0 ate 10 faca
      escreval("8 X ", contador, " = ", 8*contador)
   fimpara

fimalgoritmo


